name: Weekly Slack Poll

on:
  schedule:
    - cron: '0 1 * * 1'    # 毎週月曜01:00 UTC (= 月曜10:00 JST)
  workflow_dispatch:

jobs:
  post_poll:
    runs-on: ubuntu-latest
    steps:
      - name: Post poll to Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-Type: application/json' \
            --data '{
              "text": "*今週のキャパはどうですか？*\n:one: ◎ 余裕あり\n:two: ◯ ちょうどいい\n:three: △ 少しきつい\n:four: ✕ 大キャパり\n\nリアクションで選んでください！"
            }' \
            "$SLACK_WEBHOOK_URL"
