name: Weekly Slack Poll

on:
  schedule:
    # 毎週月曜 00:00 UTC → 09:00 JST
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  post_poll:
    runs-on: ubuntu-latest
    steps:
      - name: Post poll to Slack via Bot
        id: post
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL_ID }}
        run: |
          # JSON 組み立て
          payload=$(jq -nc \
            --arg channel "$SLACK_CHANNEL" \
            --arg text "*今週のキャパはどうですか？*\n:one: ◎ 余裕あり\n:two: ◯ ちょうどいい\n:three: △ 少しきつい\n:four: ✕ 大キャパり\n\nリアクションで選んでください！" \
            '{channel: $channel, text: $text}')
          # メッセージを Bot で投稿し、ts を取得
          resp=$(curl -s -X POST https://slack.com/api/chat.postMessage \
            -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
            -H "Content-Type: application/json" \
            --data "$payload")
          ts=$(echo "$resp" | jq -r .ts)
          # 最新の GitHub Actions 形式で出力
          echo "ts=$ts" >> $GITHUB_OUTPUT

      - name: Add default reactions
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL_ID }}
        run: |
          for name in one two three four; do
            curl -s -X POST https://slack.com/api/reactions.add \
              -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
              -H "Content-Type: application/json" \
              --data "{\"channel\":\"$SLACK_CHANNEL\",\"timestamp\":\"${{ steps.post.outputs.ts }}\",\"name\":\"$name\"}"
          done
